---
- name: Webserver Setup
  hosts: web01
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
    - name: Start Service
      service:
        name: apache2
        state: started
        enabled: yes

- name: Setup the DBserver
  hosts: dbserver
  become: yes
  tasks:
    - name: Install python3 PyMySQL
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mariadb-server
        state: present

    - name: Ensure MySQL is running
      service:
        name: mariadb
        state: started
        enabled: yes

