all:
  children:
    dev:
      hosts:
        ubuntu-dev:
          ansible_host: 52.87.252.246
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./inventory/ram.pem
    test:
      hosts:
        centos-test:
          ansible_host: 18.209.50.136
          ansible_user: ec2-user       # Update username for CentOS EC2
          ansible_ssh_private_key_file: ./inventory/ram.pem

