---
- name: Webserver Setup
  hosts: web01
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
    - name: Start Service
      service:
        name: apache2
        state: started
        enabled: yes


    - name: Copy files on ansible modules
      ansible.builtin.copy:
        src: ./files/index.html
        dest: /var/www/html/index.html
        backup: yes
