---
- name: Setup the DBserver
  hosts: dbserver
  become: yes
  tasks:
    - name: Install python3 PyMySQL
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mariadb-server
        state: present

    - name: Ensure MySQL is running
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create database user with name 'vprofile'
      community.mysql.mysql_user:
        name: vprofile
        password: 'admin943'
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
